
package com.company.task2.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculateWebService", targetNamespace = "http://webService.task1.company.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CalculateWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService.task1.company.com/CalculateWebService/additionRequest", output = "http://webService.task1.company.com/CalculateWebService/additionResponse")
    public double addition(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService.task1.company.com/CalculateWebService/subtractionRequest", output = "http://webService.task1.company.com/CalculateWebService/subtractionResponse")
    public double subtraction(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService.task1.company.com/CalculateWebService/divisionRequest", output = "http://webService.task1.company.com/CalculateWebService/divisionResponse")
    public double division(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webService.task1.company.com/CalculateWebService/multiplicationRequest", output = "http://webService.task1.company.com/CalculateWebService/multiplicationResponse")
    public double multiplication(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

}
